

## # Aula 3

- [Exceções](#exceptions)
- [Erros de tempo de execução](#runtime-errors)
- [Bloco `try`](#try)
- [Bloco `else`](#else)
- [Criando uma Função para Obter um Número Inteiro](#creating-a-function-to-get-an-integer)
- [Declaração `pass`](#pass)
- [Resumindo](#summing-up)

## Exceções

- Exceções são coisas que dão errado em nossa codificação.
- Em nosso editor de texto, digite `code hello.py` para criar um novo arquivo. Digite como segue (com os erros intencionais incluídos):

      print("hello, world)

  Observe que deixamos intencionalmente faltando uma aspa.

- Executando `python hello.py` em nossa janela do terminal, um erro é mostrado. O compilador afirma que é um "erro de sintaxe". Erros de sintaxe são aqueles que exigem que você verifique novamente se digitou a correção de código corretamente.
- Você pode aprender mais na documentação do Python sobre [Erros e Exceções](https://docs.python.org/3/tutorial/errors.html).

## Erros de tempo de execução

- Erros de tempo de execução se referem àqueles criados por comportamento inesperado dentro do seu código. Por exemplo, talvez você tenha pretendido que um usuário insira um número, mas eles inserem um caractere em vez disso. Seu programa pode lançar um erro por causa dessa entrada inesperada do usuário.
- Em sua janela do terminal, execute `code number.py`. O código é o seguinte em seu editor de texto:

      x = int(input("Qual é o valor de x? "))
      print(f"x é {x}")

  Observe que ao incluir o `f`, informamos ao Python para interpolar o que está entre os colchetes como o valor de `x`. Além disso, testando o código, você pode imaginar como alguém poderia facilmente digitar uma string ou um caractere em vez de um número. Ainda assim, um usuário poderia não digitar nada - simplesmente pressionando a tecla Enter.

- Como programadores, devemos ser defensivos para garantir que nossos usuários estejam inserindo o que esperávamos. Devemos considerar "casos extremos" como `-1`, `0` ou `cat`.
- Se executarmos esse programa e digitarmos "cat", veremos repentinamente `ValueError: invalid literal for int() with base 10: 'cat'`. Essencialmente, o interpretador do Python não gosta de passarmos "cat" para a função `print`.
- Uma estratégia eficaz para corrigir esse erro potencial seria criar uma "tratamento de erros" para garantir que o usuário se comporte conforme o pretendido.
- Você pode aprender mais na documentação do Python sobre [Erros e Exceções](https://docs.python.org/pt-br/3/tutorial/errors.html).

## `try`

- Em Python, `try` e `except` são formas de testar a entrada do usuário antes de algo dar errado. Modifique seu código da seguinte maneira:

      try:
          x = int(input("Qual é o valor de x?"))
          print(f"x é {x}")
      except ValueError:
          print("x não é um número inteiro")

  Observe como, ao executar este código, a entrada `50` será aceita. No entanto, ao digitar `cat`, um erro será exibido ao usuário, explicando por que a entrada não foi aceita.

- Ainda não é a melhor maneira de implementar esse código. Observe que estamos tentando fazer duas linhas de código. Para uma melhor prática, devemos apenas `try` as linhas de código mínimas possíveis que estamos preocupados que possam falhar. Ajuste seu código da seguinte maneira:

      try:
          x = int(input("Qual é o valor de x?"))
      except ValueError:
          print("x não é um número inteiro")

      print(f"x é {x}")

  Observe que, embora isso cumpra nosso objetivo de tentar o menor número possível de linhas, agora enfrentamos um novo erro! Enfrentamos um `NameError`, onde `x não está definido`. Observe este código e considere: por que `x` não está definido em alguns casos?

- De fato, se você examinar a ordem das operações em `x = int(input("Qual é o valor de x?"))`, trabalhando da direita para a esquerda, ele pode pegar um caractere incorretamente inserido e tentar atribuí-lo como um número inteiro. Se isso falhar, a atribuição do valor de `x` nunca ocorre. Portanto, não há `x` para ser impresso em nossa última linha de código.

## `else`

- Descobre-se que há outra maneira de implementar um `try` que pode capturar erros desse tipo.
- Ajuste seu código da seguinte forma:

      try:
          x = int(input("Qual é o valor de x?"))
      except ValueError:
          print("x não é um número inteiro")
      else:
          print(f"x é {x}")

  Observe que se nenhuma exceção ocorrer, o bloco de código dentro de `else` será executado. Executando `python number.py` e fornecendo `50`, você observará que o resultado será impresso. Tentando novamente, desta vez fornecendo `cat`, você observará que o programa agora captura o erro.

- Considerando a melhoria do nosso código, observe que estamos sendo um pouco rudes com nosso usuário. Se o usuário não cooperar, atualmente simplesmente encerramos o programa. Considere como podemos usar um loop para solicitar continuamente o valor de `x` e, caso o usuário não forneça um valor válido, pedir novamente! Melhore seu código da seguinte forma:

      while True:
          try:
              x = int(input("Qual é o valor de x?"))
          except ValueError:
              print("x não é um número inteiro")
          else:
              break

      print(f"x é {x}")

  Observe que `while True` executará o loop infinitamente. Se o usuário fornecer a entrada correta, podemos sair do loop e imprimir o resultado. Agora, um usuário que fornecer uma entrada incorreta será solicitado a fornecer outra entrada.

## Criando uma Função para Obter um Número Inteiro

- Com certeza, existem muitas vezes em que gostaríamos de obter um número inteiro do usuário. Modifique seu código da seguinte forma:

      def main():
          x = get_int()
          print(f"x é {x}")


      def get_int():
          while True:
              try:
                  x = int(input("Qual o valor de x?"))
              except ValueError:
                  print("x não é um número inteiro")
              else:
                  break
          return x


      main()

  Note que estamos manifestando várias características ótimas. Primeiro, abstraímos a capacidade de obter um número inteiro. Agora, todo o programa se resume às três primeiras linhas do programa.

- Ainda assim, podemos melhorar esse programa. Considere o que mais você poderia fazer para melhorar esse programa. Modifique seu código da seguinte forma:

      def main():
          x = get_int()
          print(f"x é {x}")


      def get_int():
          while True:
              try:
                  x = int(input("Qual o valor de x?"))
              except ValueError:
                  print("x não é um número inteiro")
              else:
                  return x


      main()

  Note que `return` não apenas interromperá o loop, mas também retornará um valor.

- Algumas pessoas podem argumentar que você poderia fazer o seguinte:

      def main():
          x = get_int()
          print(f"x é {x}")


      def get_int():
          while True:
              try:
                  return int(input("Qual o valor de x?"))
              except ValueError:
                  print("x não é um número inteiro")


      main()

  Note que isso faz a mesma coisa que a versão anterior do nosso código, apenas com menos linhas.

## `pass`

- Podemos fazer com que nosso código não avise o usuário, mas simplesmente questione novamente, modificando nosso código da seguinte maneira:

      def main():
          x = get_int()
          print(f"x é {x}")


      def get_int():
          while True:
              try:
                  return int(input("Qual é o valor de x?"))
              except ValueError:
                  pass


      main()

  Note que nosso código ainda funcionará, mas não informará repetidamente ao usuário sobre o erro. Em alguns casos, você desejará informar claramente ao usuário qual erro está sendo produzido. Em outros casos, você pode decidir apenas pedir a entrada novamente.

- Uma última melhoria que poderia melhorar a implementação dessa função `get_int`. Observamos que atualmente estamos confiando no sistema de honra de que `x` está presente tanto nas funções `main` quanto `get_int`. Provavelmente, queremos passar uma mensagem que o usuário veja ao ser solicitada a entrada. Modifique seu código da seguinte forma.

      def main():
          x = get_int("Qual é o valor de x? ")
          print(f"x é {x}")


      def get_int(prompt):
          while True:
              try:
                  return int(input(prompt))
              except ValueError:
                  pass


      main()

- Você pode obter mais informações na documentação do Python sobre [`pass`](https://docs.python.org/3/tutorial/controlflow.html#pass-statements).

## Resumindo

Erros são inevitáveis no seu código. No entanto, você tem a oportunidade de usar o que foi aprendido hoje para ajudar a prevenir esses erros. Nesta palestra, você aprendeu sobre...

- Exceções
- Erros de Valor
- Erros de Tempo de Execução
- `try`
- `else`
- `pass`